// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module "vue" {
  export interface GlobalComponents {
    AAvatar: typeof import("ant-design-vue/es")["Avatar"];
    AButton: typeof import("ant-design-vue/es")["Button"];
    ADrawer: typeof import("ant-design-vue/es")["Drawer"];
    APopover: typeof import("ant-design-vue/es")["Popover"];
  }
}

export {};
